version: "3.7"

volumes:
  shared:

services:
  api:
    build: ./http-api
    ports:
      - "3000:3000"
    volumes:
      - shared:/tmp/shared

  exporter:
    build: ./exporter
    ports:
      - "9837:9837"
    volumes:
      - shared:/tmp/shared
    depends_on:
      - api

  client:
    image: curlimages/curl
    command:
      - "/bin/sh"
      - "-c"
      - >
        while true; do
          wget -O- http://api:3000/; sleep 3;
        done
    depends_on:
      - api
